export const userAPIDummyData = {
    "success": true,
    "user_id": 1,
    "user_data": {
        "id": 1,
        "email": null,
        "username": null,
        "first_name": "Raihan",
        "last_name": "Reza",
        "customer_no": "866-916-5360",
        "company_name": "Fresh Flowers Garden",
        "billing_address": {
            "ID": 2268157,
            "post_author": "1",
            "post_date": "2025-05-08 02:31:05",
            "post_date_gmt": "2025-05-08 07:31:05",
            "post_content": "",
            "post_title": "Fresh Flowers Garden",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "closed",
            "ping_status": "closed",
            "post_password": "",
            "post_name": "fmi-raihan-reza",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2025-05-21 00:06:05",
            "post_modified_gmt": "2025-05-21 05:06:05",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://wordpress-658092-2176352.cloudwaysapps.com/user_billing_address/fmi-raihan-reza/",
            "menu_order": 0,
            "post_type": "user_billing_address",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
        },
        "shipping_address": {
            "ID": 2268010,
            "post_author": "1",
            "post_date": "2025-04-29 05:31:58",
            "post_date_gmt": "2025-04-29 10:31:58",
            "post_content": "",
            "post_title": "William Flower Gardens",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "closed",
            "ping_status": "closed",
            "post_password": "",
            "post_name": "fmi-raihan-reza-3",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2025-12-04 07:40:47",
            "post_modified_gmt": "2025-12-04 12:40:47",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "https://wordpress-658092-2176352.cloudwaysapps.com/carrier_address/fmi-raihan-reza-3/",
            "menu_order": 0,
            "post_type": "carrier_address",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
        },
        "billing_data_list": [
            {
                "billing_id": 2270105,
                "billing_company": "Fresh Flowers Garden",
                "billing_address_1": "609 E State St",
                "billing_address_2": "",
                "billing_city": "New York",
                "billing_country": "US",
                "billing_email": "karnak@elvirainfotech.com",
                "billing_first_name": "Raihan",
                "billing_last_name": "Raihan",
                "billing_postcode": "10009",
                "billing_state": "NY",
                "billing_phone": "866-916-5360",
                "bill_carrier_primary": ""
            },
            {
                "billing_id": 2268157,
                "billing_company": "Fresh Flowers Garden",
                "billing_address_1": "3136 Little Rd",
                "billing_address_2": "",
                "billing_city": "Deadhorse",
                "billing_country": "US",
                "billing_email": "karnak@elvirainfotech.com",
                "billing_first_name": "Raihan",
                "billing_last_name": "Raihan",
                "billing_postcode": "33143",
                "billing_state": "ID",
                "billing_phone": "866-916-5360",
                "bill_carrier_primary": "yes"
            }
        ],
        "shipping_data_list": [
            {
                "shipping_id": 2269783,
                "shipping_company": "Paul&#8217;s Gardens",
                "shipping_address_1": "251 Bekar St.",
                "shipping_address_2": "",
                "shipping_city": "New York",
                "shipping_country": "US",
                "shipping_email": "",
                "shipping_first_name": "William",
                "shipping_last_name": "Paul",
                "shipping_postcode": "10009",
                "shipping_state": "NY",
                "shipping_phone": "(707) 937-5804",
                "ship_carrier_primary": "yes"
            },
            {
                "shipping_id": 2269123,
                "shipping_company": "Paul&#8217;s Flower Gardens",
                "shipping_address_1": "9607 NW 33RD ST",
                "shipping_address_2": "",
                "shipping_city": "Deadhorse",
                "shipping_country": "US",
                "shipping_email": "",
                "shipping_first_name": "Paul",
                "shipping_last_name": "Walker",
                "shipping_postcode": "33156",
                "shipping_state": "IN",
                "shipping_phone": "866-916-5360",
                "ship_carrier_primary": ""
            },
            {
                "shipping_id": 2269122,
                "shipping_company": "Gabriela Flower Gardens",
                "shipping_address_1": "609 E State St",
                "shipping_address_2": "",
                "shipping_city": "Pendleton",
                "shipping_country": "US",
                "shipping_email": "",
                "shipping_first_name": "Gabriela",
                "shipping_last_name": "Gomez",
                "shipping_postcode": "46064",
                "shipping_state": "IN",
                "shipping_phone": "866-916-5360",
                "ship_carrier_primary": ""
            },
            {
                "shipping_id": 2268010,
                "shipping_company": "William Flower Gardens",
                "shipping_address_1": "360 Dalton Hwy",
                "shipping_address_2": "Dalton Street",
                "shipping_city": "Deadhorse",
                "shipping_country": "US",
                "shipping_email": "d.crespo@fmifarms.com",
                "shipping_first_name": "William",
                "shipping_last_name": "Henry",
                "shipping_postcode": "99708",
                "shipping_state": "AK",
                "shipping_phone": "(877) 474-3565",
                "ship_carrier_primary": ""
            }
        ],
        "user_data": null
    },
    "message": "user logged In"
}